spring.application.name=ScheduleTasks
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3307/scheduletasks
spring.datasource.username=root
spring.datasource.password=mysqlpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#docker run -it --network mysql-net --rm mysql mysql -hmysql -uroot -p
#docker run -d --name mysql --network mysql-net -e MYSQL_ROOT_PASSWORD=mysqlpass -p 3307:3306 mysql:9.5.0